name: goBrush
main: gc.arcaniax.gobrush.Main
version: "${version}"
author: Arcaniax
website: "http://arcaniax.net/"
description: goBrush is a plugin that's designed to streamline and simplify your mountain building experience
depend: [WorldEdit]
api-version: 1.13

commands:
  gobrush:
    description: goBrush command
    aliases: gb
permissions:
  gobrush.use:
    default: op
  gobrush.export:
    default: op
  gobrush.admin:
    default: op
  gobrush.world.bypass:
    default: op
  gobrush.bypass.maxsize:
    default: op
  gobrush.bypass.maxintensity:
    default: op