name: goBrush
main: com.arcaniax.gobrush.GoBrushPlugin
version: "${version}"
author: Arcaniax
website: "https://www.spigotmc.org/resources/23118/"
description: goBrush is a plugin that's designed to streamline and simplify your mountain building experience
depend: [WorldEdit]
api-version: 1.13

commands:
  gobrush:
    description: goBrush command
    aliases: gb
permissions:
  gobrush.use:
    default: op
  gobrush.export:
    default: op
  gobrush.admin:
    default: op
  gobrush.bypass.maxsize:
    default: op
  gobrush.bypass.maxintensity:
    default: op
